[package]
name = "modulate_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modulate_lib = {path = "../modulate_lib"}
uuid = "1.7"
log = "0.4"
pretty_env_logger = "0.5"
